version: '3'

services:

  jekyll:
    build: services/jekyll
    container_name: jekyll
    working_dir: /www
    command: jekyll serve --watch --force_polling --verbose
    volumes:
      - ./web:/www
    ports:
      - 4000:4000
